// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rlog.proto

package rlog

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogReq struct {
	MyName               string   `protobuf:"bytes,1,opt,name=MyName,proto3" json:"MyName,omitempty"`
	TimeStamp            int64    `protobuf:"varint,2,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	Log                  string   `protobuf:"bytes,3,opt,name=Log,proto3" json:"Log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogReq) Reset()         { *m = LogReq{} }
func (m *LogReq) String() string { return proto.CompactTextString(m) }
func (*LogReq) ProtoMessage()    {}
func (*LogReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_91df433c770f7314, []int{0}
}

func (m *LogReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogReq.Unmarshal(m, b)
}
func (m *LogReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogReq.Marshal(b, m, deterministic)
}
func (m *LogReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogReq.Merge(m, src)
}
func (m *LogReq) XXX_Size() int {
	return xxx_messageInfo_LogReq.Size(m)
}
func (m *LogReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LogReq.DiscardUnknown(m)
}

var xxx_messageInfo_LogReq proto.InternalMessageInfo

func (m *LogReq) GetMyName() string {
	if m != nil {
		return m.MyName
	}
	return ""
}

func (m *LogReq) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *LogReq) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

type LogRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogRsp) Reset()         { *m = LogRsp{} }
func (m *LogRsp) String() string { return proto.CompactTextString(m) }
func (*LogRsp) ProtoMessage()    {}
func (*LogRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_91df433c770f7314, []int{1}
}

func (m *LogRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRsp.Unmarshal(m, b)
}
func (m *LogRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRsp.Marshal(b, m, deterministic)
}
func (m *LogRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRsp.Merge(m, src)
}
func (m *LogRsp) XXX_Size() int {
	return xxx_messageInfo_LogRsp.Size(m)
}
func (m *LogRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LogRsp proto.InternalMessageInfo

type LogFatalReq struct {
	MyName               string   `protobuf:"bytes,1,opt,name=MyName,proto3" json:"MyName,omitempty"`
	TimeStamp            int64    `protobuf:"varint,2,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	Log                  string   `protobuf:"bytes,3,opt,name=Log,proto3" json:"Log,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogFatalReq) Reset()         { *m = LogFatalReq{} }
func (m *LogFatalReq) String() string { return proto.CompactTextString(m) }
func (*LogFatalReq) ProtoMessage()    {}
func (*LogFatalReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_91df433c770f7314, []int{2}
}

func (m *LogFatalReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogFatalReq.Unmarshal(m, b)
}
func (m *LogFatalReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogFatalReq.Marshal(b, m, deterministic)
}
func (m *LogFatalReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogFatalReq.Merge(m, src)
}
func (m *LogFatalReq) XXX_Size() int {
	return xxx_messageInfo_LogFatalReq.Size(m)
}
func (m *LogFatalReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LogFatalReq.DiscardUnknown(m)
}

var xxx_messageInfo_LogFatalReq proto.InternalMessageInfo

func (m *LogFatalReq) GetMyName() string {
	if m != nil {
		return m.MyName
	}
	return ""
}

func (m *LogFatalReq) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *LogFatalReq) GetLog() string {
	if m != nil {
		return m.Log
	}
	return ""
}

type LogFatalRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogFatalRsp) Reset()         { *m = LogFatalRsp{} }
func (m *LogFatalRsp) String() string { return proto.CompactTextString(m) }
func (*LogFatalRsp) ProtoMessage()    {}
func (*LogFatalRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_91df433c770f7314, []int{3}
}

func (m *LogFatalRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogFatalRsp.Unmarshal(m, b)
}
func (m *LogFatalRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogFatalRsp.Marshal(b, m, deterministic)
}
func (m *LogFatalRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogFatalRsp.Merge(m, src)
}
func (m *LogFatalRsp) XXX_Size() int {
	return xxx_messageInfo_LogFatalRsp.Size(m)
}
func (m *LogFatalRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LogFatalRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LogFatalRsp proto.InternalMessageInfo

type StatPointDataPB struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Data                 int64    `protobuf:"varint,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatPointDataPB) Reset()         { *m = StatPointDataPB{} }
func (m *StatPointDataPB) String() string { return proto.CompactTextString(m) }
func (*StatPointDataPB) ProtoMessage()    {}
func (*StatPointDataPB) Descriptor() ([]byte, []int) {
	return fileDescriptor_91df433c770f7314, []int{4}
}

func (m *StatPointDataPB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatPointDataPB.Unmarshal(m, b)
}
func (m *StatPointDataPB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatPointDataPB.Marshal(b, m, deterministic)
}
func (m *StatPointDataPB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatPointDataPB.Merge(m, src)
}
func (m *StatPointDataPB) XXX_Size() int {
	return xxx_messageInfo_StatPointDataPB.Size(m)
}
func (m *StatPointDataPB) XXX_DiscardUnknown() {
	xxx_messageInfo_StatPointDataPB.DiscardUnknown(m)
}

var xxx_messageInfo_StatPointDataPB proto.InternalMessageInfo

func (m *StatPointDataPB) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StatPointDataPB) GetData() int64 {
	if m != nil {
		return m.Data
	}
	return 0
}

type StatPointReq struct {
	MyName               string             `protobuf:"bytes,1,opt,name=MyName,proto3" json:"MyName,omitempty"`
	TimeStamp            int64              `protobuf:"varint,2,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	PointId              string             `protobuf:"bytes,3,opt,name=PointId,proto3" json:"PointId,omitempty"`
	DataArr              []*StatPointDataPB `protobuf:"bytes,4,rep,name=dataArr,proto3" json:"dataArr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StatPointReq) Reset()         { *m = StatPointReq{} }
func (m *StatPointReq) String() string { return proto.CompactTextString(m) }
func (*StatPointReq) ProtoMessage()    {}
func (*StatPointReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_91df433c770f7314, []int{5}
}

func (m *StatPointReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatPointReq.Unmarshal(m, b)
}
func (m *StatPointReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatPointReq.Marshal(b, m, deterministic)
}
func (m *StatPointReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatPointReq.Merge(m, src)
}
func (m *StatPointReq) XXX_Size() int {
	return xxx_messageInfo_StatPointReq.Size(m)
}
func (m *StatPointReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StatPointReq.DiscardUnknown(m)
}

var xxx_messageInfo_StatPointReq proto.InternalMessageInfo

func (m *StatPointReq) GetMyName() string {
	if m != nil {
		return m.MyName
	}
	return ""
}

func (m *StatPointReq) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *StatPointReq) GetPointId() string {
	if m != nil {
		return m.PointId
	}
	return ""
}

func (m *StatPointReq) GetDataArr() []*StatPointDataPB {
	if m != nil {
		return m.DataArr
	}
	return nil
}

type StatPointRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatPointRsp) Reset()         { *m = StatPointRsp{} }
func (m *StatPointRsp) String() string { return proto.CompactTextString(m) }
func (*StatPointRsp) ProtoMessage()    {}
func (*StatPointRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_91df433c770f7314, []int{6}
}

func (m *StatPointRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatPointRsp.Unmarshal(m, b)
}
func (m *StatPointRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatPointRsp.Marshal(b, m, deterministic)
}
func (m *StatPointRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatPointRsp.Merge(m, src)
}
func (m *StatPointRsp) XXX_Size() int {
	return xxx_messageInfo_StatPointRsp.Size(m)
}
func (m *StatPointRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_StatPointRsp.DiscardUnknown(m)
}

var xxx_messageInfo_StatPointRsp proto.InternalMessageInfo

type WarningReq struct {
	MyName               string             `protobuf:"bytes,1,opt,name=MyName,proto3" json:"MyName,omitempty"`
	TimeStamp            int64              `protobuf:"varint,2,opt,name=TimeStamp,proto3" json:"TimeStamp,omitempty"`
	Level                int32              `protobuf:"varint,3,opt,name=Level,proto3" json:"Level,omitempty"`
	Desc                 string             `protobuf:"bytes,4,opt,name=Desc,proto3" json:"Desc,omitempty"`
	DataArr              []*StatPointDataPB `protobuf:"bytes,5,rep,name=dataArr,proto3" json:"dataArr,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *WarningReq) Reset()         { *m = WarningReq{} }
func (m *WarningReq) String() string { return proto.CompactTextString(m) }
func (*WarningReq) ProtoMessage()    {}
func (*WarningReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_91df433c770f7314, []int{7}
}

func (m *WarningReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WarningReq.Unmarshal(m, b)
}
func (m *WarningReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WarningReq.Marshal(b, m, deterministic)
}
func (m *WarningReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WarningReq.Merge(m, src)
}
func (m *WarningReq) XXX_Size() int {
	return xxx_messageInfo_WarningReq.Size(m)
}
func (m *WarningReq) XXX_DiscardUnknown() {
	xxx_messageInfo_WarningReq.DiscardUnknown(m)
}

var xxx_messageInfo_WarningReq proto.InternalMessageInfo

func (m *WarningReq) GetMyName() string {
	if m != nil {
		return m.MyName
	}
	return ""
}

func (m *WarningReq) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *WarningReq) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *WarningReq) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *WarningReq) GetDataArr() []*StatPointDataPB {
	if m != nil {
		return m.DataArr
	}
	return nil
}

type WarningRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WarningRsp) Reset()         { *m = WarningRsp{} }
func (m *WarningRsp) String() string { return proto.CompactTextString(m) }
func (*WarningRsp) ProtoMessage()    {}
func (*WarningRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_91df433c770f7314, []int{8}
}

func (m *WarningRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WarningRsp.Unmarshal(m, b)
}
func (m *WarningRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WarningRsp.Marshal(b, m, deterministic)
}
func (m *WarningRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WarningRsp.Merge(m, src)
}
func (m *WarningRsp) XXX_Size() int {
	return xxx_messageInfo_WarningRsp.Size(m)
}
func (m *WarningRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_WarningRsp.DiscardUnknown(m)
}

var xxx_messageInfo_WarningRsp proto.InternalMessageInfo

type HeartBeatReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatReq) Reset()         { *m = HeartBeatReq{} }
func (m *HeartBeatReq) String() string { return proto.CompactTextString(m) }
func (*HeartBeatReq) ProtoMessage()    {}
func (*HeartBeatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_91df433c770f7314, []int{9}
}

func (m *HeartBeatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatReq.Unmarshal(m, b)
}
func (m *HeartBeatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatReq.Marshal(b, m, deterministic)
}
func (m *HeartBeatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatReq.Merge(m, src)
}
func (m *HeartBeatReq) XXX_Size() int {
	return xxx_messageInfo_HeartBeatReq.Size(m)
}
func (m *HeartBeatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatReq.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatReq proto.InternalMessageInfo

type HeartBeatRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatRsp) Reset()         { *m = HeartBeatRsp{} }
func (m *HeartBeatRsp) String() string { return proto.CompactTextString(m) }
func (*HeartBeatRsp) ProtoMessage()    {}
func (*HeartBeatRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_91df433c770f7314, []int{10}
}

func (m *HeartBeatRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatRsp.Unmarshal(m, b)
}
func (m *HeartBeatRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatRsp.Marshal(b, m, deterministic)
}
func (m *HeartBeatRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatRsp.Merge(m, src)
}
func (m *HeartBeatRsp) XXX_Size() int {
	return xxx_messageInfo_HeartBeatRsp.Size(m)
}
func (m *HeartBeatRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatRsp.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatRsp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*LogReq)(nil), "rlog.LogReq")
	proto.RegisterType((*LogRsp)(nil), "rlog.LogRsp")
	proto.RegisterType((*LogFatalReq)(nil), "rlog.LogFatalReq")
	proto.RegisterType((*LogFatalRsp)(nil), "rlog.LogFatalRsp")
	proto.RegisterType((*StatPointDataPB)(nil), "rlog.StatPointDataPB")
	proto.RegisterType((*StatPointReq)(nil), "rlog.StatPointReq")
	proto.RegisterType((*StatPointRsp)(nil), "rlog.StatPointRsp")
	proto.RegisterType((*WarningReq)(nil), "rlog.WarningReq")
	proto.RegisterType((*WarningRsp)(nil), "rlog.WarningRsp")
	proto.RegisterType((*HeartBeatReq)(nil), "rlog.HeartBeatReq")
	proto.RegisterType((*HeartBeatRsp)(nil), "rlog.HeartBeatRsp")
}

func init() { proto.RegisterFile("rlog.proto", fileDescriptor_91df433c770f7314) }

var fileDescriptor_91df433c770f7314 = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0xc7, 0xbf, 0x7c, 0x49, 0x9b, 0x76, 0x5a, 0xb5, 0x0e, 0x2a, 0xa1, 0x78, 0x28, 0xeb, 0xa5,
	0xa7, 0x16, 0x2a, 0x1e, 0x3c, 0x5a, 0x8a, 0x28, 0x44, 0x29, 0xa9, 0xe2, 0x79, 0xb5, 0x4b, 0x28,
	0xa4, 0xd9, 0x75, 0x77, 0x29, 0xf8, 0x14, 0x3e, 0x81, 0x2f, 0xe4, 0x53, 0xc9, 0x6e, 0x92, 0x26,
	0xc6, 0x8b, 0xa8, 0xb7, 0x99, 0xc9, 0xfe, 0xe7, 0xff, 0xcb, 0xcc, 0x2e, 0x80, 0x4c, 0x78, 0x3c,
	0x12, 0x92, 0x6b, 0x8e, 0x9e, 0x89, 0xc9, 0x1c, 0x9a, 0x21, 0x8f, 0x23, 0xf6, 0x8c, 0x47, 0xd0,
	0xbc, 0x79, 0xb9, 0xa5, 0x6b, 0x16, 0x38, 0x03, 0x67, 0xd8, 0x8e, 0xf2, 0x0c, 0x8f, 0xa1, 0x7d,
	0xb7, 0x5a, 0xb3, 0x85, 0xa6, 0x6b, 0x11, 0xfc, 0x1f, 0x38, 0x43, 0x37, 0x2a, 0x0b, 0xd8, 0x03,
	0x37, 0xe4, 0x71, 0xe0, 0x5a, 0x89, 0x09, 0x49, 0x2b, 0xeb, 0xa8, 0x04, 0xb9, 0x87, 0x4e, 0xc8,
	0xe3, 0x4b, 0xaa, 0x69, 0xf2, 0x97, 0x06, 0x3b, 0x95, 0xb6, 0x4a, 0x90, 0x73, 0xd8, 0x5b, 0x68,
	0xaa, 0xe7, 0x7c, 0x95, 0xea, 0x19, 0xd5, 0x74, 0x3e, 0x45, 0x04, 0x2f, 0x2d, 0x7d, 0x6c, 0x6c,
	0x6a, 0x4b, 0xaa, 0x69, 0x6e, 0x60, 0x63, 0xf2, 0xea, 0x40, 0x77, 0xab, 0xfd, 0x39, 0x62, 0x00,
	0xbe, 0xed, 0x70, 0xbd, 0xcc, 0x31, 0x8b, 0x14, 0xc7, 0xe0, 0x1b, 0xa3, 0x0b, 0x29, 0x03, 0x6f,
	0xe0, 0x0e, 0x3b, 0x93, 0xc3, 0x91, 0xdd, 0x40, 0x0d, 0x38, 0x2a, 0x4e, 0x91, 0xdd, 0x2a, 0x90,
	0x12, 0xe4, 0xcd, 0x01, 0x78, 0xa0, 0x32, 0x5d, 0xa5, 0xbf, 0xd8, 0xd1, 0x01, 0x34, 0x42, 0xb6,
	0x61, 0x89, 0xa5, 0x6b, 0x44, 0x59, 0x62, 0x06, 0x32, 0x63, 0xea, 0x29, 0xf0, 0xb2, 0x21, 0x99,
	0xb8, 0xca, 0xdb, 0xf8, 0x16, 0x6f, 0xb7, 0xc4, 0x53, 0xc2, 0xd0, 0x5f, 0x31, 0x2a, 0xf5, 0x94,
	0x51, 0x33, 0xce, 0xcf, 0xb9, 0x12, 0x93, 0x77, 0x07, 0xfc, 0x28, 0xe1, 0xf1, 0x62, 0x23, 0xf1,
	0xc4, 0xee, 0x15, 0xbb, 0x99, 0x41, 0x76, 0x07, 0xfb, 0x95, 0x4c, 0x09, 0xf2, 0x0f, 0x27, 0xd0,
	0x2a, 0x56, 0x8d, 0xfb, 0xdb, 0x6f, 0xc5, 0x8d, 0xea, 0xd7, 0x4b, 0x56, 0x73, 0x06, 0xed, 0x2d,
	0x2e, 0x62, 0x8d, 0xdf, 0xa8, 0xbe, 0xd4, 0xac, 0x6c, 0x0c, 0x7e, 0xfe, 0x27, 0xd8, 0xcb, 0x0e,
	0x94, 0x73, 0xef, 0xd7, 0x2a, 0x46, 0xf0, 0xd8, 0xb4, 0xcf, 0xe8, 0xf4, 0x23, 0x00, 0x00, 0xff,
	0xff, 0x4d, 0x43, 0xbc, 0x05, 0x54, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RlogSvrClient is the client API for RlogSvr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RlogSvrClient interface {
	Log(ctx context.Context, in *LogReq, opts ...grpc.CallOption) (*LogRsp, error)
	LogFatal(ctx context.Context, in *LogFatalReq, opts ...grpc.CallOption) (*LogFatalRsp, error)
	StatPoint(ctx context.Context, in *StatPointReq, opts ...grpc.CallOption) (*StatPointRsp, error)
	Warning(ctx context.Context, in *WarningReq, opts ...grpc.CallOption) (*WarningRsp, error)
}

type rlogSvrClient struct {
	cc *grpc.ClientConn
}

func NewRlogSvrClient(cc *grpc.ClientConn) RlogSvrClient {
	return &rlogSvrClient{cc}
}

func (c *rlogSvrClient) Log(ctx context.Context, in *LogReq, opts ...grpc.CallOption) (*LogRsp, error) {
	out := new(LogRsp)
	err := c.cc.Invoke(ctx, "/rlog.RlogSvr/Log", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rlogSvrClient) LogFatal(ctx context.Context, in *LogFatalReq, opts ...grpc.CallOption) (*LogFatalRsp, error) {
	out := new(LogFatalRsp)
	err := c.cc.Invoke(ctx, "/rlog.RlogSvr/LogFatal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rlogSvrClient) StatPoint(ctx context.Context, in *StatPointReq, opts ...grpc.CallOption) (*StatPointRsp, error) {
	out := new(StatPointRsp)
	err := c.cc.Invoke(ctx, "/rlog.RlogSvr/StatPoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rlogSvrClient) Warning(ctx context.Context, in *WarningReq, opts ...grpc.CallOption) (*WarningRsp, error) {
	out := new(WarningRsp)
	err := c.cc.Invoke(ctx, "/rlog.RlogSvr/Warning", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RlogSvrServer is the server API for RlogSvr service.
type RlogSvrServer interface {
	Log(context.Context, *LogReq) (*LogRsp, error)
	LogFatal(context.Context, *LogFatalReq) (*LogFatalRsp, error)
	StatPoint(context.Context, *StatPointReq) (*StatPointRsp, error)
	Warning(context.Context, *WarningReq) (*WarningRsp, error)
}

// UnimplementedRlogSvrServer can be embedded to have forward compatible implementations.
type UnimplementedRlogSvrServer struct {
}

func (*UnimplementedRlogSvrServer) Log(ctx context.Context, req *LogReq) (*LogRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Log not implemented")
}
func (*UnimplementedRlogSvrServer) LogFatal(ctx context.Context, req *LogFatalReq) (*LogFatalRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LogFatal not implemented")
}
func (*UnimplementedRlogSvrServer) StatPoint(ctx context.Context, req *StatPointReq) (*StatPointRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatPoint not implemented")
}
func (*UnimplementedRlogSvrServer) Warning(ctx context.Context, req *WarningReq) (*WarningRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Warning not implemented")
}

func RegisterRlogSvrServer(s *grpc.Server, srv RlogSvrServer) {
	s.RegisterService(&_RlogSvr_serviceDesc, srv)
}

func _RlogSvr_Log_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RlogSvrServer).Log(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rlog.RlogSvr/Log",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RlogSvrServer).Log(ctx, req.(*LogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RlogSvr_LogFatal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogFatalReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RlogSvrServer).LogFatal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rlog.RlogSvr/LogFatal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RlogSvrServer).LogFatal(ctx, req.(*LogFatalReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RlogSvr_StatPoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatPointReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RlogSvrServer).StatPoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rlog.RlogSvr/StatPoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RlogSvrServer).StatPoint(ctx, req.(*StatPointReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RlogSvr_Warning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WarningReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RlogSvrServer).Warning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rlog.RlogSvr/Warning",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RlogSvrServer).Warning(ctx, req.(*WarningReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RlogSvr_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rlog.RlogSvr",
	HandlerType: (*RlogSvrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Log",
			Handler:    _RlogSvr_Log_Handler,
		},
		{
			MethodName: "LogFatal",
			Handler:    _RlogSvr_LogFatal_Handler,
		},
		{
			MethodName: "StatPoint",
			Handler:    _RlogSvr_StatPoint_Handler,
		},
		{
			MethodName: "Warning",
			Handler:    _RlogSvr_Warning_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rlog.proto",
}
